name: Action

on:
  pull_request:

jobs:
  find_branch:
    name: Find a matching backend branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
          fetch-depth: 0
      - id: read_branch 
        name: Read target backend branch from PR body
        uses: begedin/variable-regex-extractor-action@v0.2.1
        with:
          pattern: "backend: \"([^\\s]+)\""
      - id: check_pr_branch
        name: Check branch in PR body
        run: |
          if [[ ${{ steps.read_branch.outputs.value }} == "" ]]; then
            found=0
          else
            echo ${{ steps.read_branch.outputs.value }}
            git show-ref --quiet ${{ steps.read_branch.outputs.value }} \
              && found=1 \
              || found=0
            echo found ${{ steps.read_branch.outputs.value }} $found
          fi
          echo ::set-output name=found::$found
      - id: check
        name: Check branch existence
        run: |
          found=1
          if [[ ${{ steps.check_pr_branch.outputs.found }} -ne 1 ]]; then
            git show-ref --quiet ${{ github.head_ref }} || found=0
            echo found ${{ github.head_ref }} $found
          fi
          echo ::set-output name=found::$found
      - id: branch
        name: Set backend branch
        run: |
          branch=main
          if [[ ${{ steps.check_pr_branch.outputs.found }} -eq 1 ]]; then
            branch=${{ steps.read_branch.outputs.value }}
          elif [[ ${{ steps.check.outputs.found }} -eq 1 ]]; then
            branch=${{ github.head_ref }}
          fi
          echo branch $branch
          echo ::set-output name=name::$branch
    outputs:
      branch_name: ${{ steps.branch.outputs.name }}

  backend_action:
    name: Backend repository run action command
    needs: find_branch
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.find_branch.outputs.branch_name }}
      - name: Checkout frontend repository
        uses: actions/checkout@v3
      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
          ref: ${{ needs.find_branch.outputs.branch_name }}
          path: backend
      - name: Run action
        run: |
          cd backend
          yarn action
