name: Action

on:
  pull_request:

env:
  BACKEND_BRANCH: ${{ GITHUB_HEAD_REF }}

jobs:
  find_branch:
    name: Find a matching backend branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
      - run: |
          echo ${{ env.BACKEND_BRANCH }}
          echo $(git remote -v)
          echo $GITHUB_HEAD_REF
          BRANCH=$GITHUB_HEAD_REF
          if git show-ref --quiet $GITHUB_HEAD_REF; then
            BRANCH=main
          fi
          echo "BACKEND_BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "BRANCH = $BRANCH"
          echo ${{ env.BACKEND_BRANCH }}

  backend_action:
    name: Backend repository run action command
    needs: find_branch
    runs-on: ubuntu-latest
    steps:
      - run: echo $BRANCH

      - run: echo ${{ env.BACKEND_BRANCH }}

      - name: Checkout frontend repository
        uses: actions/checkout@v3

      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
          ref: ${{ env.BACKEND_BRANCH }}
          path: backend

      - name: Run action
        run: |
          cd backend
          yarn action
