name: Action

on:
  pull_request:

jobs:
  find_branch:
    name: Find a matching backend branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
      - run: |
          echo ${{ env.BACKEND_BRANCH }}
          if $(git show-ref --quiet $GITHUB_HEAD_REF); then
            echo "BACKEND_BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          fi
          echo ${{ env.BACKEND_BRANCH }}
      - run: echo "${{ env.BACKEND_BRANCH }}"

  backend_action:
    name: Backend repository run action command
    needs: find_branch
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.BACKEND_BRANCH }}"

      - name: Checkout frontend repository
        uses: actions/checkout@v3

      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
          ref: ${{ env.BACKEND_BRANCH }}
          path: backend

      - name: Run action
        run: |
          cd backend
          yarn action
