name: Action

on:
  pull_request:

jobs:
  find_branch:
    name: Find a matching backend branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
      - name: Set fallback branch
        run: branch=main
      - run: |
          echo $GITHUB_HEAD_REF
          git branch | grep $GITHUB_HEAD_REF
          if [ $? -eq 0 ]; then
            echo branch=$GITHUB_HEAD_REF
          fi
      - id: branch 
        name: Set output
        run: echo ::set-output name=name::$branch
      - run: echo ${{ steps.branch.outputs.name }}
    outputs:
      branch_name: ${{ steps.branch.outputs.name }}

  backend_action:
    name: Backend repository run action command
    needs: find_branch
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.find_branch.outputs.branch_name }}"

      - name: Checkout frontend repository
        uses: actions/checkout@v3

      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
          ref: ${{ needs.find_branch.outputs.backend_branch }}
          path: backend

      - name: Run action
        run: |
          cd backend
          yarn action
