name: Action

on:
  pull_request:

jobs:
  find_branch:
    name: Find a matching backend branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
      - run: |
          echo $(git remote -v)
          echo $GITHUB_HEAD_REF
          BRANCH=main
          if git show-ref --quiet $GITHUB_HEAD_REF; then
            BRANCH=$GITHUB_HEAD_REF
          fi
          echo "BACKEND_BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "BRANCH = $BRANCH"
          echo "GITHUB_ENV = $GITHUB_ENV"
          echo "env.BACKEND_BRANCH ${{ env.BACKEND_BRANCH }}""

  backend_action:
    name: Backend repository run action command
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.BACKEND_BRANCH }}

      - name: Checkout frontend repository
        uses: actions/checkout@v3

      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: aunpyz0/fake-backend
          ref: ${{ env.BACKEND_BRANCH }}
          path: backend

      - name: Run action
        run: |
          cd backend
          yarn action
